name: C CI


on:
  push:
    branches: [main]
   #schedule:
    # - cron: '* */1 * * *' # 1時間ごと


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        working-directory: ./C
        run: |
          gcc -o mymath_test ./src/mymath.c ./tests/test_mymath.c

      - name: Run tests
        working-directory: ./C
        run: |
          ./mymath_test

  # テストが通らないケース
  # build-fail:
  #   name: Build and Test with Failure
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y build-essential

  #     - name: Build with failure
  #       run: |
  #         gcc -Wall -Wextra -o mymath_test ./C/src/mymath_fail.c ./C/tests/test_mymath.c

  #     - name: Run tests
  #       run: |
  #         ./mymath_test


  report-success:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send Success Notification
        run: echo 'Build and tests succeeded!'


  report-failure:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Failure Notification
        run: echo 'Build and tests failed!'