name: C CI


on:
  push:
    branches: [main]
   #schedule:
    # - cron: '* */1 * * *' # 1時間ごと


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          gcc -o mymath_test ./C/src/mymath.c ./C/tests/test_mymath.c

      - name: Run tests
        run: |
          ./mymath_test

  build-fail:
    name: Build and Test with Failure
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build with failure
        run: |
          gcc -Wall -Wextra -o mymath_test ./C/src/mymath_fail.c ./C/tests/test_mymath.c

      - name: Run tests
        run: |
          ./mymath_test
